<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="PersonalFinanceManagementSystem.Admin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
    body{
         font-family: Arial, sans-serif;
         margin: 0;
         padding: 0;
         background-color: #f9f9f9;
    }

    header{
        background-color: #4CAF50;
        color: white;
        text-align: center;
        padding: 10px;
    }

    nav{
        background: #333;
        padding: 10px;
        text-align: center;

    }

    nav a{
         color: white;
         margin: 0 10px;
         text-decoration: none;
         padding: 8px 15px;
    }

    nav a:hover{
        background-color: #4CAF50;
        border-radius: 5px;
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        background: white;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);

    }
 
    .card {
        padding: 20px;
        background: #f4f4f4;
        margin: 10px;
        border: 1px solid #ddd;
        text-align: center;

    }
 
    .card h3 {
        color: #4CAF50; 

    }

    footer{
        background: #333;
        color: white;
        text-align: center;
    }
     /* GridView Styling */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    table, th, td {
        border: 1px solid #ddd;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    .GridView a {
        text-decoration: none;
        padding: 5px 10px;
        background-color: #4CAF50;
        color: white;
        border-radius: 3px;
    }

    .GridView a:hover {
        background-color: #45a049;
    }

        .auto-style1 {
            text-align: center;
        }

        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 617px;
        }

    </style>
</head>
<body>
            <header><h1>Personal Finance Management System</h1></header>
                <nav>
    <a href="Dashboard.aspx">Dashboard</a>
    <a href="Transaction.aspx">Transaction</a>
    <a href="Notification.aspx">Set Notification</a>
    <a href="Report.aspx">Report</a>
    <a href="Account.aspx">Account</a>
</nav>

    <form id="form1" runat="server">
    <h2 class="auto-style1"> User managment<br />
        <table class="auto-style2">
            <tr>
                <td class="auto-style3">Name </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">Email</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">Password</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">Phone no.</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style1" colspan="2">
                    <asp:Button ID="btnup" runat="server" Text="Update" />
                </td>
            </tr>
        </table>
        </h2>
        <asp:GridView ID="grvshow" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CssClass="GridView" OnRowDeleting="grvshow_RowDeleting">
</asp:GridView>
        <div>

        </div>
    </form>
            <p>
&nbsp;</p>
</body>
</html>
